---
version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/src/agent"
      - "/src/dragonball"
      - "/src/libs"
      - "/src/mem-agent"
      - "/src/mem-agent/example"
      - "/src/runtime-rs"
      - "/src/runtime-rs/crates/hypervisor"
      - "/src/tools/agent-ctl"
      - "/src/tools/genpolicy"
      - "/src/tools/kata-ctl"
      - "/src/tools/runk"
      - "/src/tools/trace-forwarder"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directories:
      - "/src/runtime"
      - "tools/testing/kata-webhook/go.mod"
      - "src/tools/csi-kata-directvolume/go.mod"
    schedule:
      interval: "weekly"
