---
version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/src/agent"
      - "/src/dragonball"
      - "/src/dragonball/dbs_utils/"
      - "/src/dragonball/dbs_virtio_devices"
      - "/src/dragonball/dbs_pci"
      - "/src/libs"
      - "/src/mem-agent"
      - "/src/runtime-rs"
      - "/src/runtime-rs/crates/hypervisor"
      - "/src/tools/agent-ctl"
      - "/src/tools/genpolicy"
      - "/src/tools/kata-ctl"
      - "/src/tools/runk"
      - "/src/tools/trace-forwarder"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directories:
      - "/src/runtime"
    schedule:
      interval: "weekly"
