on:
  schedule:
    - cron: '0 5 * * *'

name: Nightly CI for s390x

permissions:
  contents: read

jobs:
  check-internal-test-result:
    runs-on: s390x
    strategy:
      fail-fast: false
      matrix:
        test_title:
          - kata-vfio-ap-e2e-tests
          - cc-vfio-ap-e2e-tests
          - cc-se-e2e-tests
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - name: Fetch a test result for {{ matrix.test_title }}
      run: |
        file_name="${TEST_TITLE}-$(date +%Y-%m-%d).log"
        "/home/${USER}/script/handle_test_log.sh" download "$file_name"
      env:
        TEST_TITLE: ${{ matrix.test_title }}
