name: CI | Run kubernetes tests on AKS
on:
  workflow_dispatch

jobs:
  run-k8s-tests:
    strategy:
      fail-fast: false
      matrix:
        host_os:
          - ubuntu
        vmm:
          - clh
          - dragonball
          - qemu
          - qemu-runtime-rs
          - stratovirt
          - cloud-hypervisor
        instance-type:
          - small
          - normal
        include:
          - host_os: cbl-mariner
            vmm: clh
            instance-type: small
            genpolicy-pull-method: oci-distribution
            auto-generate-policy: yes
          - host_os: cbl-mariner
            vmm: clh
            instance-type: small
            genpolicy-pull-method: containerd
            auto-generate-policy: yes
          - host_os: cbl-mariner
            vmm: clh
            instance-type: normal
            auto-generate-policy: yes
    runs-on: ubuntu-22.04
    env:
      KATA_HOST_OS: ${{ matrix.host_os }}
      KATA_HYPERVISOR: ${{ matrix.vmm }}
      KUBERNETES: "vanilla"
      USING_NFD: "false"
      K8S_TEST_HOST_TYPE: ${{ matrix.instance-type }}
      GENPOLICY_PULL_METHOD: ${{ matrix.genpolicy-pull-method }}
      AUTO_GENERATE_POLICY: ${{ matrix.auto-generate-policy }}
    steps:
      - name: Install kata
        run: |
          echo "AUTO_GENERATE_POLICY: ${AUTO_GENERATE_POLICY}"
