name: CI | Run kubernetes tests on AKS
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
      pr-number:
        required: true
        type: string
      commit-hash:
        required: false
        type: string
      target-branch:
        required: false
        type: string
        default: ""

jobs:
  run-k8s-tests:
    strategy:
      fail-fast: false
      matrix:
        rust-runtime:
          - false
        host_os:
          - ubuntu
        vmm:
          - clh
          - dragonball
          - qemu
          - stratovirt
        instance-type:
          - small
          - normal
        include:
          - host_os: cbl-mariner
            vmm: clh
          - dragonball:
            rust-runtime: true
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ inputs.registry }}
      DOCKER_REPO: ${{ inputs.repo }}
      DOCKER_TAG: ${{ inputs.tag }}
      GH_PR_NUMBER: ${{ inputs.pr-number }}
      KATA_HOST_OS: ${{ matrix.host_os }}
      KATA_HYPERVISOR: ${{ matrix.vmm }}
      KUBERNETES: "vanilla"
      USING_NFD: "false"
      K8S_TEST_HOST_TYPE: ${{ matrix.instance-type }}
      RUST_RUNTIME: ${{ matrix.rust-runtime }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Dummy step
        run: |
          echo "Dummy test won't run required as they are renamed"
